### ISSUE TITLE
Move to a build / release process safely

### ISSUE THREAD

**Issue by SeanKilleen** [excellalabs/unanet-summarizer#32]
This issue is meant to be the plan that drives several PRs to get us to a spot where we have a build / release process and thus can take advantage of modern tooling / libraries to accomplish the next steps we need.

## Goals

* Nobody has to update the bookmarklet they're using
* Bookmarklet performance isn't compromised
* Don't break functionality as we go
* We can use modern libraries & tooling
* We can preview the script (e.g. staging)

## Proposed Steps (in order)

* [x] (#33, #34) Create a duplicate script in the repository, so that it will also be served from GitHub Pages.
* [x] (#35) Update our current script to load an additional script tag that loads that duplicated script (essentially accomplishing a redirect)
* [x] (#31) Create a build process
* [x] (#49) Set up CI / build process (Azure DevOps most likely)
* [x] (#49) Create a release process with prod (and preview?) destinations
* [x] ~~(#55) Add CSS file to the build output~~ already done, unnecessary
* [x] (#57) Switch our redirect script to use the release output locations
* [x] (#58) Delete the files that live in the repo -- now fully reliant on the build.
* [x] (#58) Add some comments to the redirect piece because it'd seem confusing / unnecessary to someone who didn't know the history.

## Boxes for CI/CD to check

* [x] Lives in the repo as much as possible
* [x] Publicly viewable
* [x] Builds all PRs
* [x] Builds master with same step
* [x] Release process that serves the output of dist
* [x] Reasonably fast
* [x] Documented (maybe move dev stuff to separate MD file?)

## Nice to haves 
(can move to other issues if we run out of time)

* [ ] Preview area with preview bookmarklet
* [ ] Announce to the slack channel when a release is published
* [ ] Do we want an official release process with release notes and have them passed along too?

**Comment by SeanKilleen** [comment]
@jmweir thoughts on this?

**Comment by jmweir** [comment]
I think this is a viable process

**Comment by SeanKilleen** [comment]
@jmweir FYI, everything is now going based on our build system in production.

✅ Bookmarklet loads
✅ Build process works (and documented in #49)
✅ Old files removed ✅

Therefore, closing this out! 🚀 :shipit:
